export enum InputKeys {
    ArrowUp = 'ArrowUp',
    ArrowDown = 'ArrowDown',
    ArrowLeft = 'ArrowLeft',
    ArrowRight = 'ArrowRight',
    Space = 'Space',
    Enter = 'Enter',
    Pause = 'Pause',
    Shift = 'Shift',
    Ctrl = 'Control',
    Alt = 'Alt',
    W = 'KeyW', 
    A = 'KeyA', 
    S = 'KeyS', 
    D = 'KeyD', 
    C = 'KeyC', 
    Z = 'KeyZ', 
    Q = 'KeyQ', 
    E = 'KeyE',
    R = 'KeyR',
    P = 'KeyP',
    T = 'KeyT',
    B = 'KeyB',
}